# Generated by Django 3.0.3 on 2020-03-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_tag',
            field=models.ManyToManyField(null=True, to='articles.Tag'),
        ),
    ]
