# Generated by Django 3.0.3 on 2020-03-06 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200306_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 19, 25, 25, 414872)),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
