# Generated by Django 3.0.3 on 2020-03-06 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200306_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 19, 46, 11, 748019)),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_img',
            field=models.ImageField(blank=True, default='articles/happy_lion.jpg', null=True, upload_to='articles'),
        ),
    ]
